### PR TITLE
!Feature: Main game interface

### LINKED ISSUE #13: Render the game board with tiles and empty spaces
Might need to refactor code. We have basically everything for you to start working on the UI.

### LINKED ISSUE #26: Bug when moving diagonally
Even though I implemented a revert mechanics to handle the exception raises when accessing land out of bound, it wasn't perfect.

Pressing W and A at the same time (when at any edge), it will add two of em at the same time to eventManager which at a result, moving to invalid postition and cannot revert.

### LINKED ISSUE #27: Main Game UI
Construction of a wireframe UI, with premade stub for textures later down the line.

The UI need to be able to convey all intended game information, including but not limited to:

- Board state (tile placed + *current* score) of all player
- Play Order
- Upcoming tiles

### LINKED ISSUE #32: Bug in GameScreen after populated
After playing some round, the camera/game seems to zoom in, cutting game info.

> *this is an image of the top up corner when it zoomed and cut out game info*
image

### LINKED ISSUE #36: Abnormality during Turn Selection
## Description

Latest commit to `features/main-game-interface` (#eff045a) exhibits irregularities when selecting domino.

## Reproduction Step

1. First player select the first domino in the upcoming set
2. Second player select 3rd/4th domino in the upcoming set

### Expected Behavior

The selected domino by the second player should be marked off as selected.

### Actual Behavior

A different domino is marked as selected, while the intended domino is not.

### Note

The UI for selecting domino is not working properly so any irregularities there is to be expected. However it is certain that the UI can show which domino is claimed by players, and the terminal UI should be showing which domino is currently "selected" (not confirmed) by the player, of which this irregularity shows.

### PR DESCRIPTION
**Pull request by LunaciaDev**
This PR track the progress of implementing said feature. Requirement can be found in linked issue.

TODO (not exhaustive):

- [x] Construct a minimal UI for the main game loop
    - [x] Division of Screen Space
    - [x] Player Board
    - [x] Dominoes
    - [x] Scoring
    - [x] Turn Order
    - [x] Leaderboard
    - [x] Upcoming Dominoes
    - [x] Other player's information side
    - [x] Picking next domino
    - [x] Highlight selected domino when picking one for next round
    - [x] Highlight turn on turn order
- [x] Texture stubs (allow loading texture once we have them)

Known Bugs:
- [x] #31 (won't fix unless if we have time for it)
- [x] #32 
- [x] #36

### CODE REVIEW

**Comment by LunaciaDev** [comment]
A bit too fast on this XD need to differ from the base branch (feature/user-interface first). Will reopen once there is a diff.

**Review by fuisl — COMMENTED** [review]
Impressive

File: core/src/main/java/dev/kingdomino/screen/GameScreen.java [hunk 1]
```diff
@@ -2,39 +2,38 @@
...
     }
 
     @Override
     public void initScreen() {
+        screenViewport = new ScreenViewport();
+        stage = new Stage(screenViewport);
         gameManager = new GameManager();
+        // TODO remove later, just pinging to get it to be alive... I assume
+        // why do you need to be pinged twice...?
+        gameManager.update(0f);
```
Comment (fuisl) [inline core/src/main/java/dev/kingdomino/screen/GameScreen.java:54]: I don't get this. Why do you call update with dt=0f and why twice??

**Review by fuisl — COMMENTED** [review]
Except for the ping twice, everything looks good to me.

File: core/src/main/java/dev/kingdomino/screen/GameScreen.java (hunk 1 above)
Comment (LunaciaDev) [reply core/src/main/java/dev/kingdomino/screen/GameScreen.java:54]: First update run make the gameManager do the init part, Second update run make gameManager do the setup() part, by then everything is ready for rendering.

Comment (LunaciaDev) [reply core/src/main/java/dev/kingdomino/screen/GameScreen.java:54]: 0f is placeholder value as it is just to get the gameManager to wake up

**Comment by LunaciaDev** [comment]
8414f9e is population, it does not work too well yet (or at all, I presume)

**Comment by LunaciaDev** [comment]
Meant to reference issue #32 in the commit.

**Comment by LunaciaDev** [comment]
@fuisl Not sure how would one get a score of the board from the backend. Last few playtest saw the score not changing...

**Comment by fuisl** [comment]
> @fuisl Not sure how would one get a score of the board from the backend. Last few playtest saw the score not changing...

Every `Board` hold a `ScoringSystem` component, which will have to manually call `calculateLandScore()` as implemented in every `placeDomino()` command in `class GameManager`. It should be working for every placing domino.

To get the score for each Board, I exposed the scoringSystem, you can call `getLandTotal()`, `getBoardTotal()` and `getLandBonus()`.

**Comment by LunaciaDev** [comment]
> > @fuisl Not sure how would one get a score of the board from the backend. Last few playtest saw the score not changing...
> 
> Every `Board` hold a `ScoringSystem` component, which will have to manually call `calculateLandScore()` as implemented in every `placeDomino()` command in `class GameManager`. It should be working for every placing domino.
> 
> To get the score for each Board, I exposed the scoringSystem, you can call `getLandTotal()`, `getBoardTotal()` and `getLandBonus()`.


image
image

The score should be 2 in this case, but it is returning 0?

**Comment by fuisl** [comment]
@LunaciaDev 

> > > @fuisl Not sure how would one get a score of the board from the backend. Last few playtest saw the score not changing...
> > 
> > 
> > Every `Board` hold a `ScoringSystem` component, which will have to manually call `calculateLandScore()` as implemented in every `placeDomino()` command in `class GameManager`. It should be working for every placing domino.
> > To get the score for each Board, I exposed the scoringSystem, you can call `getLandTotal()`, `getBoardTotal()` and `getLandBonus()`.
> 
> image image
> 
> The score should be 2 in this case, but it is returning 0?

Turned out that you were right! The Flood Fill algorithm didn't access the right Tile. But ironically, I didn't realize the bug since I put the Tiles in the diagonal line. The algorithm still detect and still flooding, it just need to pass the very first case to init the chain reaction.

Fixed in PR #34

**Comment by LunaciaDev** [comment]
Oh right, highlighting which domino is selected for next turn

**Comment by LunaciaDev** [comment]
So while the UI is ready, there's a couple thing that would need patching up on the backend:

- [x] Right now game logic is also bound to the backend renderer, which mean realistically we cannot remove it, maybe just trimming off the printing part? (Fixed in 0774a69)
- [x] After drafting a domino, even though which domino is selected is tracked via an array, it is still removed from the drafting list AND affect which index is being selected (so if one domino is selected, selectionIndex will go from 0 - 2 instead of 0 - 3, which is later translated back to 0 - 3??), so the highlight selected domino is not behaving properly. (Fixed in 9cc10f0)

**Comment by LunaciaDev** [comment]
Also this is just minimal UI without any proper texture/animation yet, next priority would be getting texture, then animation, and finally sound. After that, maybe some extra screen like menu, loading and stuff.

**Comment by LunaciaDev** [comment]
@fuisl should be ready for reviewing.

**Comment by LunaciaDev** [comment]
Is there a way for gameManager to keep a sorted version of Kings' scores?

**Comment by fuisl** [comment]
> Is there a way for gameManager to keep a sorted version of Kings' scores?

to sort the King by the scores? or to just have a sorted score without regarding the owner of that score? Both cases are possible.

**Comment by LunaciaDev** [comment]
Having the Kings sorted by score would be best.

**Comment by fuisl** [comment]
> Having the Kings sorted by score would be best.

Actually long ago, I've already implemented a `LinkedHashMap<King, int[]` for King and an array containing the total score (inc. bonus). I can "implement" an update for every King that has just finished their round (or place their current Domino). 

> _you can check these code out in `GameManager`_

```java
private void results() {
          scores = new LinkedHashMap<King, int[]>();
          
          // get scores for render
          for (King k : kings) {
              int landScore = k.getBoard().getScoringSystem().getLandTotal();
              int bonusScore = k.getBoard().getScoringSystem().getLandBonus();
              int totalScore = k.getBoard().getScoringSystem().getBoardTotal();
              scores.put(k, new int[] { landScore, bonusScore, totalScore });
          }

          scores = sortScores(scores, 2); // sort by total
}

private Map<King, int[]> sortScores(Map<King, int[]> scores, int sortIndex) {
    LinkedHashMap<King, int[]> sortedScores = scores.entrySet().stream()
            .sorted((entry1, entry2) -> Integer.compare(entry2.getValue()[sortIndex], entry1.getValue()[sortIndex]))
            .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (e1, e2) -> e1, LinkedHashMap::new));
    return sortedScores;
}
 ```
 
However, I'm not so sure if you'd want to display the total (inc. bonus) or just the land scores (w/o bonus). Since in the middle of the game, one could get bonus (Castle tile in the middle) and later it could degrade. Would you want the bonus update accordingly also?

But for calculating and sort the `score` variable would be possible since I already implemented that.

**Comment by fuisl** [comment]
However I do see that we can just sort the `King[] kings` by their scores. But as I mentioned, I'd want things to be clear and maybe another variable like `Map score` would be better in terms of "separate of concerns" principle. What's your opinion on this @LunaciaDev ?

**Comment by LunaciaDev** [comment]
Main reason I want gameManger to handle the sorting of score is that it can be made not to update too often.

If the UI does that, it’ll sort the score every frame and that’s not very desirable.

For displaying, total score only should be good enough?

**Comment by fuisl** [comment]
Like mentioned earlier. The bonus will make the score jump during game (says you have spanned 3x3 and score jumped). Now I mentioned that, I could use the strategy to span just 3x3 and discard any placing to earn the bonus. Ok will  call result() to update scores accordingly. You should try to work with Map<King, int[]> to retrieve the sorted scoreboard.

**Review by fuisl — COMMENTED** [review]
Perfect!

**Review by fuisl — COMMENTED** [review]
We have our game.

**Review by fuisl — APPROVED** [review]
